import type { Question } from '@/types/quiz'

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    step: 1,
    type: 'text',
    prompt: 'What was your biggest W this month?',
    subtext: 'Any win counts — big or small.',
    emoji: '🏆',
    config: {
      placeholder: 'e.g. Finally finished that project, got the promotion, didn\'t text back…',
      maxLength: 280,
      rows: 3,
    },
    required: true,
  },
  {
    id: 'q2',
    step: 2,
    type: 'text',
    prompt: 'What was your most painful L?',
    subtext: 'Be honest. We won\'t judge.',
    emoji: '💀',
    config: {
      placeholder: 'e.g. Lost that client, overslept a big meeting, sent the wrong text…',
      maxLength: 280,
      rows: 3,
    },
    required: true,
  },
  {
    id: 'q3',
    step: 3,
    type: 'slider',
    prompt: 'On a scale of 1–10, how broke were you?',
    subtext: '1 = actually ate well, 10 = selling plasma for groceries.',
    emoji: '💸',
    config: {
      min: 1,
      max: 10,
      step: 1,
      emojis: {
        1: '🤑',
        2: '💰',
        3: '💵',
        4: '🫰',
        5: '😐',
        6: '😬',
        7: '😰',
        8: '😭',
        9: '💀',
        10: '⚰️',
      },
      labels: { min: 'Thriving', max: 'Cooked' },
    },
    required: true,
  },
  {
    id: 'q4',
    step: 4,
    type: 'slider',
    prompt: 'How was your sleep game?',
    subtext: 'Be real about those 3am doom-scroll sessions.',
    emoji: '😴',
    config: {
      min: 1,
      max: 10,
      step: 1,
      emojis: {
        1: '🧟',
        2: '😵',
        3: '😪',
        4: '🥱',
        5: '😐',
        6: '🙂',
        7: '😌',
        8: '😴',
        9: '🌙',
        10: '✨',
      },
      labels: { min: 'Deranged', max: 'Sleeping like royalty' },
    },
    required: true,
  },
  {
    id: 'q5',
    step: 5,
    type: 'yes-no',
    prompt: 'Did you ghost anyone this month? 👻',
    subtext: 'Left on read counts.',
    emoji: '👻',
    config: {
      yesLabel: 'Yes 😬',
      noLabel: 'No (angel) 😇',
      followUpPrompt: 'Who was the victim? (no names required)',
    },
    required: true,
  },
  {
    id: 'q6',
    step: 6,
    type: 'text',
    prompt: 'Best meal that carried you this month?',
    subtext: 'The one you\'re still thinking about.',
    emoji: '🍽️',
    config: {
      placeholder: 'e.g. Jollof rice at mom\'s, that random shawarma at 2am, instant noodles…',
      maxLength: 150,
      rows: 2,
    },
    required: true,
  },
  {
    id: 'q7',
    step: 7,
    type: 'text',
    prompt: 'Most unhinged thing you did?',
    subtext: 'No shame zone. This is a safe space.',
    emoji: '🌀',
    config: {
      placeholder: 'e.g. Texted my ex at 2am, booked a flight on impulse, cried at a commercial…',
      maxLength: 280,
      rows: 3,
    },
    required: true,
  },
  {
    id: 'q8',
    step: 8,
    type: 'text',
    prompt: 'One lesson the universe tried to teach you?',
    subtext: 'Did you learn it though?',
    emoji: '🌌',
    config: {
      placeholder: 'e.g. Slow down, stop people-pleasing, rest is productive…',
      maxLength: 200,
      rows: 2,
    },
    required: true,
  },
  {
    id: 'q9',
    step: 9,
    type: 'multiple-choice',
    prompt: 'Situationship status update?',
    subtext: 'Current relationship to relationships.',
    emoji: '💘',
    config: {
      options: [
        'Single and thriving 👑',
        'It\'s complicated 🤷',
        'Deeply in love 🥰',
        'Healing (again) 💔',
        'Happily unbothered 😎',
        'Dating chaos 🌪️',
      ],
      allowCustom: true,
      customPlaceholder: 'It\'s a whole other situation…',
    },
    required: true,
  },
  {
    id: 'q10',
    step: 10,
    type: 'slider',
    prompt: 'How many times did you say "I\'m healing"?',
    subtext: 'Or think it. Counts too.',
    emoji: '🌱',
    config: {
      min: 0,
      max: 10,
      step: 1,
      emojis: {
        0: '😐',
        1: '🙂',
        2: '🌱',
        3: '🌿',
        4: '🌊',
        5: '✨',
        6: '💫',
        7: '🕯️',
        8: '🧘',
        9: '🌸',
        10: '🦋',
      },
      labels: { min: 'Not once', max: 'My whole personality' },
      unit: 'times',
    },
    required: true,
  },
  {
    id: 'q11',
    step: 11,
    type: 'text',
    prompt: 'Song that defined your month?',
    subtext: 'The one on repeat at 3am.',
    emoji: '🎵',
    config: {
      placeholder: 'e.g. "vampire" – Olivia Rodrigo, or paste a Spotify link…',
      maxLength: 200,
      rows: 2,
    },
    required: true,
  },
  {
    id: 'q12',
    step: 12,
    type: 'slider',
    prompt: 'Fitness – glow-up or glow-down?',
    subtext: '1 = couch fused with body, 10 = could run a marathon tomorrow.',
    emoji: '💪',
    config: {
      min: 1,
      max: 10,
      step: 1,
      emojis: {
        1: '🛋️',
        2: '🐌',
        3: '🐢',
        4: '🚶',
        5: '🏃',
        6: '💦',
        7: '🏋️',
        8: '⚡',
        9: '🔥',
        10: '🏆',
      },
      labels: { min: 'Glow-down era', max: 'Peak performance' },
    },
    required: true,
  },
  {
    id: 'q13',
    step: 13,
    type: 'text',
    prompt: 'One person who kept you sane this month?',
    subtext: 'Your unsung MVP.',
    emoji: '🫂',
    config: {
      placeholder: 'e.g. My sister, my therapist, my group chat, my cat…',
      maxLength: 150,
      rows: 2,
    },
    required: true,
  },
  {
    id: 'q14',
    step: 14,
    type: 'slider',
    prompt: 'Rate your main character energy this month.',
    subtext: '1 = background extra, 10 = Oscar-winning performance.',
    emoji: '🎬',
    config: {
      min: 1,
      max: 10,
      step: 1,
      emojis: {
        1: '🤏',
        2: '😔',
        3: '🙁',
        4: '😑',
        5: '😐',
        6: '🙂',
        7: '😎',
        8: '⭐',
        9: '🌟',
        10: '👑',
      },
      labels: { min: 'Background extra', max: 'Main character' },
    },
    required: true,
  },
  {
    id: 'q15',
    step: 15,
    type: 'text',
    prompt: 'One word to sum up this month.',
    subtext: 'Make it count.',
    emoji: '💬',
    config: {
      placeholder: 'e.g. Chaotic, Growth, Tired, Blessed, Unbothered…',
      maxLength: 30,
      rows: 1,
    },
    required: true,
  },
]

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id)
}

export function getQuestionByStep(step: number): Question | undefined {
  return QUESTIONS.find((q) => q.step === step)
}

export const TOTAL_STEPS = QUESTIONS.length
